### ISSUE TITLE
Alternative way of estimating posteriors and statistics for FeatureImportanceForestClassifier

### ISSUE THREAD

**Issue by sampan501** [neurodata/treeple#194]
From @jovo 

**Is your feature request related to a problem? Please describe.**
We sometimes get lower power with `FeatureImportanceForestClassifier` than previous methods, and one possible explanation is our 40-40-20 splits doesn't use very much data to learn tree structures or estimate posteriors well.

**Describe the solution you'd like**
1. Bootstrap samples n times
2. Split those in half, one set for learning the tree and one set for learning the posterior
3. Use OOB samples for estimating the posterior
4. Average across trees to estimate posteriors
5. Estimate all the statistics we want

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by PSSF23** [comment]
The only difference of this method, compared to `sampling_per_tree=True`, seems to be sampling with replacement instead of no replacement. But wouldn't this method potentially result in very inconsistent numbers of OOB samples for each tree? Also, wouldn't we actually have fewer distinct samples to learn tree structures?

Suppose we have 100 samples, we bootstrap 100 times. The possibility of one sample to be OOB is (99/100)^100 = 0.366. So on average, only 64 distinct samples would be selected, and 14~50 distinct samples used for learning tree structures or estimating posteriors. Overall, I don't believe this method gives more data to each tree. I believe it adds more variance than `sampling_per_tree=True`.

**Comment by SUKI-O** [comment]
@PSSF23 Isn't 64 distinct samples on avg is better than the current 40-40-20 though, no?

**Comment by jovo** [comment]
there are a few differences:

1. the number of unique data points in each subset of data
2. that some data points might be represented in both tree structure and posterior learning
3. but each tree has a different set of points in tree/posterior/statistic subset.  this is the most important step.  once we have this step working, we can try bootstrapping with and without replacement, etc.

**Comment by PSSF23** [comment]
@SUKI-O The current 40-40-20 gives 80 distinct samples to each tree. Which is "better" I don't have a belief yet. I'm disagreeing with 

> 40-40-20 splits doesn't use very much data to learn tree structures or estimate posteriors well. 


I agree with what jovo says, that each tree now has a unique subset of data.

**Comment by adam2392** [comment]
We've since converged on the idea of:

- bootstrap per tree such that 80% unique samples are in-bag and 20% are oob
- split the 80% in-bag into structure and leaf node samples for training the tree and fitting the posterior function estimate
- use 20% oob to estimate statistic
